package com.yiming.contextlens

import android.content.Context
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL
import java.time.Instant

data class Session(val token:String,val userId:String,val email:String)
data class Word(val id:String,val contextId:String,val word:String,val meaning:String,val hint:String,val phonetic:String,val meanings:List<String>,val nextReview:String,val sentence:String,val translation:String)
data class DictionaryResult(val word:String,val phonetic:String,val meanings:List<String>)

object Config { const val SUPABASE_URL="https://zlybpcaeubirmcdtcuvg.supabase.co";const val SUPABASE_KEY="sb_publishable_E10YsdTduoIdJMpmQpqsHA_6pYjAHWE" }

class Api(private val context:Context) {
    private val prefs=context.getSharedPreferences("context_lens",Context.MODE_PRIVATE)
    var session:Session?=prefs.getString("session",null)?.let{runCatching{JSONObject(it)}.getOrNull()}?.let{Session(it.getString("token"),it.getString("userId"),it.getString("email"))}
    private fun call(url:String,method:String="GET",body:JSONObject?=null,auth:Boolean=true):String{val c=(URL(url).openConnection() as HttpURLConnection).apply{requestMethod=method;connectTimeout=15000;readTimeout=25000;setRequestProperty("Content-Type","application/json");setRequestProperty("apikey",Config.SUPABASE_KEY);if(auth)session?.let{setRequestProperty("Authorization","Bearer ${it.token}")};if(body!=null){doOutput=true;outputStream.use{o->o.write(body.toString().toByteArray())}}};val code=c.responseCode;val text=(if(code<400)c.inputStream else c.errorStream)?.bufferedReader()?.readText().orEmpty();if(code>=400)throw Exception(runCatching{JSONObject(text).optString("message",text)}.getOrDefault(text));return text}
    suspend fun auth(email:String,password:String,signUp:Boolean):String=withContext(Dispatchers.IO){val path=if(signUp)"/auth/v1/signup" else "/auth/v1/token?grant_type=password";val root=JSONObject(call(Config.SUPABASE_URL+path,"POST",JSONObject().put("email",email).put("password",password),false));if(!root.has("access_token"))return@withContext "请查收验证邮件后再登录";val user=root.getJSONObject("user");session=Session(root.getString("access_token"),user.getString("id"),user.optString("email",email));prefs.edit().putString("session",JSONObject().put("token",session!!.token).put("userId",session!!.userId).put("email",session!!.email).toString()).apply();"登录成功"}
    fun signOut(){session=null;prefs.edit().remove("session").apply()}
    suspend fun loadWords():List<Word> = withContext(Dispatchers.IO){val contexts=JSONArray(call("${Config.SUPABASE_URL}/rest/v1/study_contexts?select=id,sentence,translation&deleted_at=is.null"));val contextMap=(0 until contexts.length()).associate{val row=contexts.getJSONObject(it);row.getString("id") to row};val rows=JSONArray(call("${Config.SUPABASE_URL}/rest/v1/study_words?select=*&deleted_at=is.null&order=next_review_at.asc"));(0 until rows.length()).map{rows.getJSONObject(it)}.mapNotNull{row->val source=contextMap[row.getString("context_id")]?:return@mapNotNull null;val meaningsJson=row.optJSONArray("meanings")?:JSONArray();val meanings=(0 until meaningsJson.length()).map{meaningsJson.optString(it)}.filter{it.isNotBlank()};Word(row.getString("id"),row.getString("context_id"),row.getString("word"),row.optString("meaning"),row.optString("review_hint"),row.optString("phonetic"),if(meanings.isEmpty())listOf(row.optString("meaning"))else meanings,row.optString("next_review_at",Instant.EPOCH.toString()),source.optString("sentence"),source.optString("translation"))}.filter{runCatching{Instant.parse(it.nextReview)<=Instant.now()}.getOrDefault(true)}}
    suspend fun rate(item:Word,days:Int)=withContext(Dispatchers.IO){val next=Instant.now().plusSeconds(days*86400L).toString();val c=(URL("${Config.SUPABASE_URL}/rest/v1/study_words?id=eq.${item.id}").openConnection() as HttpURLConnection).apply{requestMethod="PATCH";setRequestProperty("Content-Type","application/json");setRequestProperty("apikey",Config.SUPABASE_KEY);setRequestProperty("Authorization","Bearer ${session!!.token}");setRequestProperty("Prefer","return=minimal");doOutput=true;outputStream.use{it.write(JSONObject().put("next_review_at",next).toString().toByteArray())}};if(c.responseCode>=400)throw Exception(c.errorStream?.bufferedReader()?.readText().orEmpty())}
    suspend fun dictionary(query:String):DictionaryResult=withContext(Dispatchers.IO){prefs.getString("dict_${query.lowercase()}",null)?.let{return@withContext parseDictionary(it)};val c=URL("https://api.dictionaryapi.dev/api/v2/entries/en/${java.net.URLEncoder.encode(query,"UTF-8")}").openConnection() as HttpURLConnection;c.connectTimeout=12000;c.readTimeout=18000;val text=if(c.responseCode<400)c.inputStream.bufferedReader().readText()else throw Exception("没有找到这个单词");prefs.edit().putString("dict_${query.lowercase()}",text).apply();parseDictionary(text)}
    private fun parseDictionary(text:String):DictionaryResult{val root=JSONArray(text).getJSONObject(0);val meanings=root.getJSONArray("meanings");val defs=mutableListOf<String>();for(i in 0 until meanings.length()){val m=meanings.getJSONObject(i);val part=m.optString("partOfSpeech");val rows=m.getJSONArray("definitions");if(rows.length()>0)defs += "$part · ${rows.getJSONObject(0).getString("definition")}"};return DictionaryResult(root.getString("word"),root.optString("phonetic"),defs)}
}

class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{ContextApp(Api(this))}}}

@Composable fun ContextApp(api:Api){var tab by remember{mutableIntStateOf(if(api.session==null)2 else 0)};val colors=lightColorScheme(primary=Color(0xFF1D6B54),background=Color(0xFFF7F5EE),surface=Color(0xFFFFFEFA));MaterialTheme(colorScheme=colors){Scaffold(bottomBar={NavigationBar{NavigationBarItem(tab==0,{tab=0},{Icon(Icons.Outlined.Refresh,null)},label={Text("复习")});NavigationBarItem(tab==1,{tab=1},{Icon(Icons.Outlined.Search,null)},label={Text("查词")});NavigationBarItem(tab==2,{tab=2},{Icon(Icons.Outlined.Person,null)},label={Text("账户")})}}){padding->Box(Modifier.padding(padding).fillMaxSize().background(colors.background)){when(tab){0->ReviewScreen(api);1->DictionaryScreen(api);else->AccountScreen(api){tab=0}}}}}}

@Composable fun Header(title:String,subtitle:String){Column(Modifier.padding(22.dp,22.dp,22.dp,10.dp)){Text(title,style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.SemiBold);Text(subtitle,color=Color.Gray,style=MaterialTheme.typography.bodySmall)}}

@Composable fun ReviewScreen(api:Api){val scope=rememberCoroutineScope();var list by remember{mutableStateOf<List<Word>>(emptyList())};var loading by remember{mutableStateOf(false)};var error by remember{mutableStateOf("")};var revealed by remember{mutableStateOf(false)};var chineseFirst by remember{mutableStateOf(false)};fun reload(){scope.launch{loading=true;runCatching{api.loadWords()}.onSuccess{list=it;revealed=false}.onFailure{error=it.localizedMessage.orEmpty()};loading=false}};LaunchedEffect(api.session){if(api.session!=null)reload()};Column{Header("今日复习","每个单词独立安排，完成后自动进入下一个");if(api.session!=null)Row(Modifier.padding(horizontal=18.dp),verticalAlignment=Alignment.CenterVertically){Text("复习方式");Spacer(Modifier.width(12.dp));FilterChip(!chineseFirst,{chineseFirst=false;revealed=false},{Text("英文答中文")});Spacer(Modifier.width(8.dp));FilterChip(chineseFirst,{chineseFirst=true;revealed=false},{Text("中文答英文")})};when{api.session==null->Empty("请先登录","登录后会同步 Mac 收藏的词汇");loading->Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){CircularProgressIndicator()};list.isEmpty()->Empty("今天复习完成","新收藏会自动安排复习");else->{val item=list.first();Card(Modifier.padding(18.dp).fillMaxWidth(),shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(22.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){Text(if(chineseFirst)item.meanings.firstOrNull().orEmpty() else item.word,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);if(!chineseFirst&&item.phonetic.isNotBlank())Text(item.phonetic,color=Color.Gray);Text(if(chineseFirst)"请回答对应的英文" else "请回答中文意思",color=Color.Gray);if(revealed){HorizontalDivider();Text(if(chineseFirst)item.word else item.meanings.joinToString("；"),style=MaterialTheme.typography.titleMedium);Text(item.sentence,fontStyle=FontStyle.Italic);Text(item.translation,color=Color.Gray);if(item.hint.isNotBlank())Text("提示：${item.hint}")}else Button({revealed=true}){Text("显示答案")};if(revealed)Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){listOf("忘记" to 0,"模糊" to 1,"记得" to 4).forEach{(label,days)->Button({scope.launch{api.rate(item,days);list=list.drop(1);revealed=false}}){Text(label)}}}}}}};if(error.isNotEmpty())Text(error,color=MaterialTheme.colorScheme.error,modifier=Modifier.padding(18.dp))}}

@Composable fun DictionaryScreen(api:Api){val scope=rememberCoroutineScope();var query by remember{mutableStateOf("")};var result by remember{mutableStateOf<DictionaryResult?>(null)};var status by remember{mutableStateOf("")};Column{Header("免费词典","无需 AI，查询结果会缓存到手机");Row(Modifier.padding(horizontal=18.dp),verticalAlignment=Alignment.CenterVertically){OutlinedTextField(query,{query=it},Modifier.weight(1f),singleLine=true,label={Text("输入英文单词")});Spacer(Modifier.width(8.dp));Button({scope.launch{status="查询中…";runCatching{api.dictionary(query.trim())}.onSuccess{result=it;status=""}.onFailure{status=it.localizedMessage.orEmpty()}}},enabled=query.isNotBlank()){Text("查询")}};result?.let{Card(Modifier.padding(18.dp).fillMaxWidth()){Column(Modifier.padding(20.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text(it.word,style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Text(it.phonetic,color=Color.Gray);it.meanings.forEach{d->Text(d)}}}};if(status.isNotEmpty())Text(status,Modifier.padding(18.dp))}}

@Composable fun AccountScreen(api:Api,onLogin:()->Unit){val scope=rememberCoroutineScope();var email by remember{mutableStateOf("")};var password by remember{mutableStateOf("")};var signUp by remember{mutableStateOf(false)};var status by remember{mutableStateOf("")};Column{Header("账户与同步","Mac 与 Android 使用同一个词库");Card(Modifier.padding(18.dp).fillMaxWidth()){Column(Modifier.padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){if(api.session!=null){Text(api.session!!.email,fontWeight=FontWeight.Bold);Text("收藏和复习进度将通过 Supabase 同步");OutlinedButton({api.signOut();status="已退出"}){Text("退出登录")}}else{SingleChoiceSegmentedButtonRow{SegmentedButton(!signUp,{signUp=false},shape=SegmentedButtonDefaults.itemShape(0,2)){Text("登录")};SegmentedButton(signUp,{signUp=true},shape=SegmentedButtonDefaults.itemShape(1,2)){Text("注册")}};OutlinedTextField(email,{email=it},label={Text("邮箱")},singleLine=true);OutlinedTextField(password,{password=it},label={Text("密码")},singleLine=true);Button({scope.launch{status="请稍候…";runCatching{api.auth(email.trim(),password,signUp)}.onSuccess{status=it;if(api.session!=null)onLogin()}.onFailure{status=it.localizedMessage.orEmpty()}}},enabled=email.contains("@")&&password.length>=6){Text(if(signUp)"创建账户" else "登录")}};if(status.isNotEmpty())Text(status,style=MaterialTheme.typography.bodySmall)}}}}

@Composable fun Empty(title:String,description:String){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Outlined.School,null,Modifier.size(48.dp),tint=Color.Gray);Text(title,fontWeight=FontWeight.Bold);Text(description,color=Color.Gray)}}}
